name: Bake CSV into HTML (bash only)

on:
  push:
    paths:
      - data/oris_data.csv
      - docs/index.tmpl.html
      - .github/workflows/bake-data-into-html.yml
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sanity check files
        shell: bash
        run: |
          set -euo pipefail
          ls -la
          ls -la docs || true
          ls -la data || true
          test -f docs/index.tmpl.html || { echo "ERROR: docs/index.tmpl.html not found"; exit 1; }
          test -f data/oris_data.csv   || { echo "ERROR: data/oris_data.csv not found"; exit 1; }
          if grep -q "__ORIS_DATA__" docs/index.tmpl.html; then
            echo "Found __ORIS_DATA__ token in template."
          elif grep -q "<!--DATA:START-->" docs/index.tmpl.html; then
            echo "Found DATA markers."
          else
            echo "WARNING: No placeholder found in template."
          fi

      - name: Convert CSV -> JSON (awk, mapped fields)
        shell: bash
        run: |
          set -euo pipefail
          CSV="data/oris_data.csv"
          JSON="data/oris_data.json"

          awk -v FPAT='([^,]+)|(\"([^\"]|\"\")*\")' '
            function json_escape(s){ gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); gsub(/\r_
