name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # allow pushing with GITHUB_TOKEN

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install (binary) R packages
        run: |
          apt-get update
          apt-get install -y \
            git ca-certificates \
            r-cran-tidyverse r-cran-rvest r-cran-xml2 \
            r-cran-stringr r-cran-purrr r-cran-readr

      - name: Run scraper
        run: |
          Rscript scrape_oris.R

      - name: Commit & push changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Automated scrape: $(date -u +'%Y-%m-%dT%H:%M:%SZ') [skip ci]"
          git pull --rebase origin "${GITHUB_REF_NAME}"
          git push origin HEAD:"${GITHUB_REF_NAME}"
