# from a local clone (or use the web editor)
git checkout main
mkdir -p .github/workflows
printf '%s\n' "\
name: Scrape ORIS daily
on:
  schedule:
    - cron: '10 4 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  run-r:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: rocker/r2u:24.04
    defaults:
      run:
        working-directory: \${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Install tools and CRAN binaries
        run: |
          apt-get update
          apt-get install -y git ca-certificates
          apt-get install -y \
            r-cran-tidyverse r-cran-rvest r-cran-xml2 \
            r-cran-stringr r-cran-purrr r-cran-readr
      - name: Run scraper
        run: Rscript scrape_oris.R
      - name: Commit & push new data (if changed)
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory \"\$GITHUB_WORKSPACE\"
          git config user.name  \"github-actions[bot]\"
          git config user.email \"41898282+github-actions[bot]@users.noreply.github.com\"
          if ls data/*.csv >/dev/null 2>&1; then git add data/*.csv; fi
          if ! git diff --cached --quiet; then
            git commit -m \"chore: update ORIS scrape (\$(date +'%Y-%m-%d'))\"
            git push
          else
            echo \"No data changes to commit.\"
          fi
" > .github/workflows/scrape.yml
git add .github/workflows/scrape.yml
git commit -m "Add scrape workflow"
git push
