name: Scrape ORIS daily

on:
  schedule:
    # Runs at 04:10 UTC (≈ 06:10 Prague during CEST). Adjust as you like.
    - cron: "10 4 * * *"
  workflow_dispatch: {}

permissions:
  contents: write   # allow committing CSVs back to the repo

jobs:
  run-r:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Use a container that already has R preinstalled
    container:
      image: rocker/r2u:24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install CRAN binaries via apt (fast, no compiling)
        run: |
          apt-get update
          # tidyverse pulls a lot in one go; extra packages listed explicitly for clarity
          apt-get install -y \
            r-cran-tidyverse \
            r-cran-rvest \
            r-cran-xml2 \
            r-cran-stringr \
            r-cran-purrr \
            r-cran-readr

      - name: Show R session (sanity check)
        run: Rscript -e 'sessionInfo()'

      - name: Run scraper
        run: Rscript scrape_oris.R

      - name: Commit & push new data (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ORIS scrape ($(date +'%Y-%m-%d'))"
          file_pattern: data/*.csv
