name: scrape

on:
  schedule:
    - cron: "40 13 * * *"   # 13:40 UTC → 15:40 Prague (CEST), 14:40 CET in winter
  workflow_dispatch: {}      # enables manual run from Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Add your scraping steps here. Example:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scrape.py
