name: Scrape ORIS daily

on:
  schedule:
    - cron: "10 4 * * *"   # 04:10 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-r:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    container:
      image: rocker/r2u:24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # needed for pushing commits

      - name: Install runtime tools (git) + CRAN binaries
        run: |
          apt-get update
          apt-get install -y git ca-certificates
          apt-get install -y \
            r-cran-tidyverse \
            r-cran-rvest \
            r-cran-xml2 \
            r-cran-stringr \
            r-cran-purrr \
            r-cran-readr

      - name: (Optional) mark workspace safe for git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Show R session (sanity check)
        run: Rscript -e 'sessionInfo()'

      - name: Run scraper
        run: Rscript scrape_oris.R

      - name: Commit & push new data (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ORIS scrape ($(date +'%Y-%m-%d'))"
          file_pattern: data/*.csv
