name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:24.04
      # IMPORTANT: do NOT override -w, GitHub mounts the repo at /__w/<repo>/<repo>
      # If you do need it, use /__w/obcicd/obcicd

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system packages and R packages (from binaries)
        run: |
          apt-get update
          apt-get install -y \
            git ca-certificates \
            r-cran-tidyverse r-cran-rvest r-cran-xml2 \
            r-cran-stringr r-cran-purrr r-cran-readr

      - name: Run scraper
        run: Rscript scrape_oris.R
        # No working-directory override needed;
        # $GITHUB_WORKSPACE already points to /__w/obcicd/obcicd
